### ISSUE TITLE
Consider changing graph implementation

### ISSUE THREAD

**Issue by alberdingk-thijm** [princedpw/nv#12]
The current nv graph implementation in `datastructures/AdjGraph.ml` is very basic.
I've added a little functionality to allow nodes to be added, but I gradually find myself needing to tack on bits.

I spoke to @princedpw about this and his suggestion was to pull in a more complete OCaml graph library to replace `AdjGraph.ml`. I'd like to look into the available options and see about replacing the current library with something a little heftier.

**Comment by nickgian** [comment]
[Here's a pointer](https://opam.ocaml.org/packages/ocamlgraph/)
I've used this in multiple projects, for NV too (fun fact: the module AdjGraph was named Graph initially but clashed with OCamlgraph forcing me to rename it).

**Comment by alberdingk-thijm** [comment]
@nickgian Yeah, that's what I was thinking we'd use. I'll start a separate branch and hack something together.
