### ISSUE TITLE
Update SMT encoding to handle TGet and TSet

### ISSUE THREAD

**Issue by DKLoehr** [princedpw/nv#14]
Currently we transform TGets and TSets which can't be immediately simplified into match statements during partial evaluation. But it should be possible to leave them until SMT encoding, and then encode them directly. Doing this would be much more efficient since we don't have to create intermediate variables, and we might be able to actually shrink the SMT encoding of irrelevant tuple elements.

**Comment by nickgian** [comment]
See PR #28.
