### ISSUE TITLE
Rare Unix exception during SMT solving

### ISSUE THREAD

**Issue by DKLoehr** [princedpw/nv#15]
I've very rarely run into the following error when running the SMT solver (stacktrace included on the offchance it's helpful:

Fatal error: exception Unix.Unix_error(Unix.EMFILE, "pipe", "")
Raised by primitive operation at file "src/lib/smt/SolverUtil.ml", line 26, characters 28-58
Called from file "src/lib/smt/Smt.ml", line 148, characters 15-34
Called from file "src/lib/Main_defs.ml", line 94, characters 10-60
Called from file "src/lib/utils/Profile.ml", line 10, characters 12-16
Called from file "src/lib/Main_defs.ml", line 139, characters 8-146
Called from file "src/exe/Main.ml", line 21, characters 12-37
Called from file "src/lib/utils/Profile.ml", line 10, characters 12-16
Called from file "src/exe/Main.ml", line 31, characters 2-67

I've only seen it twice and so far it hasn't been repeatable. The most recent time was during network slicing: it failed on slice number 125 (out of 500). All the slices should be isomorphic. It's rare, but it completely crashes NV, so it's a pain if it happens during a really long execution (like it did above). I don't have a great grasp of the system calls happening here; anyone else have any ideas?

**Comment by nickgian** [comment]
The exception EMFILE means that the process has opened too many files, in this case pipes to a z3 process. I don't think I've placed proper cleanup code for old pipes (whatever old means) as it used to be the case that you will run only 1 instance of z3. Once NV is done the pipes are closed automatically. This is probably only observable in the context of slicing where depending on how you implemented things you fork a new z3 process and a new pipe for each slice.

Fixes should be:
1. You don't fork a new z3 process for every slice, instead you reuse the existing z3 process. Maybe fork N processes if you do parallelism. But in general there is an overhead to forking new processes so there should be reuse.
2. Implement proper cleanup of open channels.
