### ISSUE TITLE
Add a continuous integration (CI) tool, e.g. Travis

### ISSUE THREAD

**Issue by alberdingk-thijm** [princedpw/nv#17]
Since nv has a pretty nice test suite now, one usability feature we might want to consider is adding a CI tool like [Travis](https://travis-ci.com/) to automatically run `make` and `make test` for us and check that new code doesn't break anything.

I think adding this will require someone with access to the repo settings to give Travis permissions to run, and will also need someone to write a `.travis.yml` file. Both should be pretty straightforward.

**Comment by DKLoehr** [comment]
Update: Dave set this up, so now we just need to get the scripts working.
