### ISSUE TITLE
Z3 error: non-diff logic expression

### ISSUE THREAD

**Issue by DKLoehr** [princedpw/nv#26]
Attempting to solve columbus with slicing yields the following error: 
(smt.diff_logic: non-diff logic expression ...) 
followed by an enormous expression. Looking through it, the expression contains a multiplication by -1 which is not present in the original program.

It seems like this is a reoccurrence of an [old z3 issue](https://github.com/Z3Prover/z3/issues/1266). We should probably try to verify that this is a z3 bug, and if so let the z3 team know. Nick, have you run into anything like this before?

Example invocation:
```
./nv -m -unbox -slicing examples/columbus/columbus.nv
```

**Comment by nickgian** [comment]
OK this seems to be a Z3 issue. If you disable the tactic solve-eqs it works (which can be a temporary workaround). Do you want to create a github issue for the Z3 folks?

**Comment by DKLoehr** [comment]
Oh, nice. Yeah, I'll try to pare our example down, then make an issue on the z3 repo.
