### ISSUE TITLE
Bug during smt encoding of assertions with option comparisons after unboxing

### ISSUE THREAD

**Issue by DKLoehr** [princedpw/nv#8]
I'm getting exception Invalid_argument("List.map2: list lengths differ") when I run the following commands:

make install
./nv -m -unbox examples/debugging/option-comparison.nv

A cursory examination indicates that the issue is that the assertion encoding is (correctly) returning one variable to represent the output of the assertion, but it's returning two expressions to represent the comparison at the end (which, after unboxing, is a tuple comparison, so it's returning one comparison for each component). I'm not sure what the correct fix is, and this is orthogonal to my current work, so for the moment I'm going to leave it as is.

In the meantime, we can use a workaround: instead of writing
`x[3] = None`
which is bad practice anyway, write

1. match x[3] with
2. | None -> true
3. | Some _ -> false

**Comment by nickgian** [comment]
I bumped into this on the iBGP example too. Will get to it at some point, thanks for documenting it!

**Comment by nickgian** [comment]
Fixed in [abae315](https://github.com/princedpw/nv/commit/abae315eaef28bb3908d12b41fae38a4526bb073).
